Repository Rakesh9100/Beautiify, pull requests merged in 2024-01, with the labels that each got.

#131 Added UI to the components cards and carousels
  Components/Cards/Drag-&-Drop-Card/style.css
  Components/Cards/Flip-Card/background-image.jpg
  Components/Cards/Flip-Card/index.html
  Components/Cards/Flip-Card/style.css
  Components/Cards/Glassmorphism-Card/style.css
  Components/Carousels/3D-Image-Carousel/style.css
  Components/Carousels/Image-Carousel/style.css
  Components/Carousels/Simple-Carousel/index.html
  Components/Carousels/Simple-Carousel/style.css
  Components/Carousels/Strip-Carousel/style.css
Labels: question 🤔

#127 Added Dynamic Gradient Background
  Components/Backgrounds/Dynamic-Gradient-Background/index.html
  Components/Backgrounds/Dynamic-Gradient-Background/style.css
  assets/html_files/backgrounds.html
Labels: question 🤔

#148 Added Stylist Scroll bar
  style.css
Labels: question 🤔

#185 Added Overlay navbar
  Components/Navigation-Bars/Overlay-Navigation-Bar/index.html
  Components/Navigation-Bars/Overlay-Navigation-Bar/script.js
  Components/Navigation-Bars/Overlay-Navigation-Bar/styles.css
  assets/html_files/navigation-bars.html
Labels: SWOC S4, Easy, Completed 🥳

#217 Added Payment Form
  Components/Forms/Payment-Form/index.html
  Components/Forms/Payment-Form/style.css
  assets/html_files/forms.html
Labels: Medium, Completed 🥳, JWOC

#220 Added new component category : Footers
  Components/Footers/Waves-Footer/index.html
  Components/Footers/Waves-Footer/style.css
  assets/css_files/footers.css
  assets/html_files/footers.html
  index.html
Labels: Hard, Completed 🥳, IWOC2024

#219 Created and linked seperate contributors page
  assets/css_files/contributor.css
  assets/html_files/accordions.html
  assets/html_files/backgrounds.html
  assets/html_files/breadcrumbs.html
  assets/html_files/buttons.html
  assets/html_files/cards.html
  assets/html_files/carousels.html
  assets/html_files/contact.html
  assets/html_files/contributor.html
  assets/html_files/forms.html
  assets/html_files/loaders.html
  assets/html_files/navigation-bars.html
  assets/html_files/search-bars.html
  assets/html_files/text-animations.html
  index.html
  style.css
Labels: Medium, Completed 🥳, JWOC

#225 Added Frosted Glass Loader
  Components/Loaders/Frosted-Glass-Loader/index.html
  Components/Loaders/Frosted-Glass-Loader/script.js
  Components/Loaders/Frosted-Glass-Loader/style.css
  assets/html_files/loaders.html
Labels: question 🤔

#226 Added a 3-D Side Navigation bar
  Components/Navigation-Bars/3D-Reveal-Side-Navigation-Bar/index.html
  Components/Navigation-Bars/3D-Reveal-Side-Navigation-Bar/style.css
  assets/html_files/navigation-bars.html
Labels: SWOC S4, Hard, Completed 🥳

#227 Added pipeline animation background
  Components/Backgrounds/Pipeline-Animation-Background/index.html
  Components/Backgrounds/Pipeline-Animation-Background/js/noise.min.js
  Components/Backgrounds/Pipeline-Animation-Background/js/pipeline.js
  Components/Backgrounds/Pipeline-Animation-Background/js/util.js
  Components/Backgrounds/Pipeline-Animation-Background/style.css
  assets/html_files/backgrounds.html
Labels: SWOC S4, Hard, Completed 🥳

#231 Added new 3-D Animated card in cards component.
  Components/Cards/3D-Animated-Card/index.html
  Components/Cards/3D-Animated-Card/style.css
  assets/html_files/cards.html
Labels: Easy, Completed 🥳, IWOC2024

#228 Added Numbered Navigation Bar
  Components/Navigation-Bars/Numbered-Navigation-Bar/index.html
  Components/Navigation-Bars/Numbered-Navigation-Bar/script.js
  Components/Navigation-Bars/Numbered-Navigation-Bar/style.css
  assets/html_files/navigation-bars.html
Labels: SWOC S4, Hard, Completed 🥳

#252 Added Neumorphic Search Bar
  Components/Search-Bars/Neumorphic-Search-Bar/index.html
  Components/Search-Bars/Neumorphic-Search-Bar/script.js
  Components/Search-Bars/Neumorphic-Search-Bar/styles.css
  assets/html_files/search-bars.html
Labels: question 🤔

#244 Added Feedback form
  Components/Forms/Feedback-Form/background.jpeg
  Components/Forms/Feedback-Form/feedback.css
  Components/Forms/Feedback-Form/feedback.html
  assets/html_files/forms.html
Labels: question 🤔

#259 Polaroid Like Photo Carousel
  Components/Carousels/Polaroid-Like-Photo-Carousel/index.html
  Components/Carousels/Polaroid-Like-Photo-Carousel/style.css
  assets/html_files/carousels.html
Labels: question 🤔

#271 Added Revolving Carousel
  Components/Carousels/Revolving-Carousel/index.html
  Components/Carousels/Revolving-Carousel/styles.css
  assets/html_files/carousels.html
Labels: question 🤔

#292 New Voice command search bar added
  Components/Search-Bars/Voice-Command-Search-Bar/app.js
  Components/Search-Bars/Voice-Command-Search-Bar/index.html
  Components/Search-Bars/Voice-Command-Search-Bar/style.css
  assets/html_files/search-bars.html
Labels: question 🤔

#288 Contact Form component made responsive on small devices
  Components/Forms/Contact-Form/index.html
  Components/Forms/Contact-Form/style.css
Labels: question 🤔

#310 Added Navigator Breadcrumb
  Components/Breadcrumbs/Navigator-Breadcrumb/index.html
  Components/Breadcrumbs/Navigator-Breadcrumb/script.js
  Components/Breadcrumbs/Navigator-Breadcrumb/styles.css
  assets/html_files/breadcrumbs.html
Labels: question 🤔

#312 Added glassmorphism search bar
  Components/Search-Bars/Glassmorphism-Search-Bar/index.html
  Components/Search-Bars/Glassmorphism-Search-Bar/style.css
  assets/html_files/search-bars.html
Labels: question 🤔

#309 Responsiveness of parallax background
  Components/Backgrounds/Parallax-Background/index.html
  Components/Backgrounds/Parallax-Background/style.css
Labels: question 🤔

#323 Added Animated Breadcrumb
  Components/Breadcrumbs/Animated-Breadcrumb/index.html
  Components/Breadcrumbs/Animated-Breadcrumb/script.js
  Components/Breadcrumbs/Animated-Breadcrumb/style.css
  assets/html_files/breadcrumbs.html
Labels: question 🤔

#194 Added the Chatbot
  assets/Chatbot.txt
  index.html
  style.css
Labels: question 🤔

#345 Added Rippling Neumorphic Loader
  Components/Loaders/Rippling-Neumorphic-Loader/index.html
  Components/Loaders/Rippling-Neumorphic-Loader/script.js
  Components/Loaders/Rippling-Neumorphic-Loader/styles.css
  assets/html_files/loaders.html
Labels: question 🤔

#357 Added Parallel Park Breadcrumb
  Components/Breadcrumbs/Parallel-Park-Breadcrumb/index.html
  Components/Breadcrumbs/Parallel-Park-Breadcrumb/styles.css
  assets/html_files/breadcrumbs.html
Labels: question 🤔

#327 Rounded Square Background Animation Added
  Components/Backgrounds/Rounded-Square-Animation-Background/index.html
  Components/Backgrounds/Rounded-Square-Animation-Background/styles.css
  assets/html_files/backgrounds.html
Labels: question 🤔

#372 Added validation to the contact form
  assets/html_files/contact.html
Labels: question 🤔

#382 Added 3d cylindrically rotating text animation
  Components/Backgrounds/Colour-Drop-Background/index.css
  Components/Text-Animations/3D-Cylindrically-Rotating-Text-Animation/index.html
  Components/Text-Animations/3D-Cylindrically-Rotating-Text-Animation/style.css
  Components/Text-Animations/3D-Cylindrically-Rotating-Text-Animation/style.css.map
  Components/Text-Animations/3D-Cylindrically-Rotating-Text-Animation/style.scss
  assets/html_files/text-animations.html
Labels: question 🤔

#377 Added an about us section
  assets/css_files/about.css
  assets/html_files/about.html
  assets/html_files/accordions.html
  assets/html_files/backgrounds.html
  assets/html_files/breadcrumbs.html
  assets/html_files/buttons.html
  assets/html_files/cards.html
  assets/html_files/carousels.html
  assets/html_files/contact.html
  assets/html_files/contributor.html
  assets/html_files/footers.html
  assets/html_files/forms.html
  assets/html_files/loaders.html
  assets/html_files/navigation-bars.html
  assets/html_files/search-bars.html
  assets/html_files/text-animations.html
  index.html
  style.css
Labels: Hard, Completed 🥳, IWOC2024

#395 Added a new square loader
  Components/Loaders/Square-Loader/index.html
  Components/Loaders/Square-Loader/style.css
  assets/html_files/loaders.html
Labels: question 🤔

#398 Added Tilted Accordion
  Components/Accordions/Tilted-Accordion/index.html
  Components/Accordions/Tilted-Accordion/style.css
  assets/html_files/accordions.html
Labels: question 🤔

#422 Added File Upload Form
  Components/Forms/File-Upload-Form/index.html
  Components/Forms/File-Upload-Form/script.js
  Components/Forms/File-Upload-Form/styles.css
  assets/html_files/forms.html
Labels: Hard, Completed 🥳, IWOC2024

#434 Added Icons to navigation bar
  assets/html_files/accordions.html
  assets/html_files/backgrounds.html
  assets/html_files/breadcrumbs.html
  assets/html_files/buttons.html
  assets/html_files/cards.html
  assets/html_files/carousels.html
  assets/html_files/contributor.html
  assets/html_files/footers.html
  assets/html_files/forms.html
  assets/html_files/loaders.html
  assets/html_files/navigation-bars.html
  assets/html_files/search-bars.html
  assets/html_files/text-animations.html
Labels: question 🤔

#461 Added voice command feature to search bar
  script.js
  style.css
Labels: question 🤔

#472 Added Animated SignIn Form
  Components/Forms/Animated-SignIn-Form/index.html
  Components/Forms/Animated-SignIn-Form/style.css
  assets/html_files/forms.html
Labels: question 🤔

#468 Added Gradient Stroke & Bounce Loader
  Components/Loaders/Gradient-Stroke-Bounce-Loader/index.html
  Components/Loaders/Gradient-Stroke-Bounce-Loader/style.css
  assets/html_files/loaders.html
Labels: question 🤔

#492 Added Playlist Carousel
  Components/Carousels/Playlist-Carousel/index.html
  Components/Carousels/Playlist-Carousel/script.js
  Components/Carousels/Playlist-Carousel/style.css
  assets/html_files/carousels.html
Labels: question 🤔
